import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, X, User, CreditCard, MapPin, Briefcase, Users, ShieldAlert, Camera, FileText, Calendar } from 'lucide-react';
import { parseEgyptianNationalId } from '../utils/nationalId';

const INITIAL = (b) => ({batch_id:b?.id||1,attendance_date:new Date().toISOString().split('T')[0],name:'',religion:'مسلم',qualification:'متوسط',national_id:'',birth_date:'',wife:'أعزب',address:'',current_job:'بدون عمل',other_jobs:'لا يوجد',travel_abroad:'لم يسافر خارج البلاد',literacy:'يجيد القراءة والكتابة',inspection:'بنية جيدة - لا توجد علامات مميزة أو وشم - سلوك معتدل',medical_status:'لائق طبياً وسليم ظاهرياً',father_name:'',father_job:'عامل',mother_name:'',mother_job:'ربة منزل',siblings_check:'لا توجد ملاحظات أمنية على الأشقاء',family_social_status:'الأسرة مستقرة والوالدان على قيد الحياة',family_security_status:'العائلة خالية من السوابق والشبهات الجنائية والسياسية',police_number:'',company:'السرية الثالثة ( ٣ )'});
const STEPS=[{id:'identity',label:'البيانات الأساسية',icon:User,fields:['name','national_id','birth_date','religion','qualification','wife','address','police_number']},{id:'background',label:'البيانات والتصنيف',icon:FileText,fields:['current_job','other_jobs','travel_abroad','literacy','inspection','medical_status','company']},{id:'family',label:'البيانات العائلية',icon:Users,fields:['father_name','father_job','mother_name','mother_job','siblings_check','family_social_status','family_security_status']}];
const LABELS={name:'الاسم الرباعي',national_id:'الرقم القومي',birth_date:'تاريخ الميلاد',religion:'الديانة',qualification:'المؤهل الدراسي',wife:'الحالة الاجتماعية',address:'عنوان السكن',police_number:'رقم الشرطة',current_job:'المهنة الحالية',other_jobs:'مهن وحرف أخرى',travel_abroad:'السفر خارج البلاد',literacy:'إجادة القراءة والكتابة',inspection:'مناظرة المجند',medical_status:'الحالة المرضية',company:'السرية / الكتيبة',father_name:'اسم الوالد',father_job:'مهنة الوالد',mother_name:'اسم الأم',mother_job:'مهنة الأم',siblings_check:'فحص الإخوة',family_social_status:'الحالة الاجتماعية للعائلة',family_security_status:'الحالة الأمنية للعائلة'};
const OPTIONS={religion:['مسلم','مسيحي'],qualification:['عالي','فوق متوسط','متوسط','عادة','محو أمية'],wife:['أعزب','متزوج','مطلق'],current_job:['عامل','سائق','نجار','حداد','محاسب','مدرس','طالب','بدون عمل'],other_jobs:['لا يوجد','كهربائي','سباك','مبلط','ميكانيكي','نقاش'],travel_abroad:['لم يسافر خارج البلاد','سافر للعمل بالخارج','سافر للسياحة'],literacy:['يجيد القراءة والكتابة','يقرأ ويكتب بصعوبة','لا يجيد (أمي)'],father_job:['على المعاش','عامل','مزارع','موظف حكومي','سائق','تاجر','متوفى'],mother_job:['ربة منزل','موظفة','معلمة','متوفاة'],company:['السرية الأولى ( ١ )','السرية الثانية ( ٢ )','السرية الثالثة ( ٣ )','السرية الرابعة ( ٤ )','السرية الخامسة ( ٥ )','السرية السادسة ( ٦ )']};
const TEXTAREA=['inspection','medical_status','siblings_check','family_security_status'];

function ChoiceField({label,value,options,onChange}){return <div><label className="block text-xs font-bold text-slate-300 mb-2">{label}</label><div className="flex flex-wrap gap-2">{options.map(o=><button type="button" key={o} onClick={()=>onChange(o)} className={`px-3 py-2 text-xs font-bold border transition-colors ${value===o?'bg-[var(--amn-blue-50)] border-[#4c6fff] text-white':'bg-[var(--ui-bg)] border-[var(--ui-border)] text-slate-400 hover:text-white hover:bg-white/5'}`}>{o}</button>)}</div></div>}

export default function KioskForm({activeBatch,onComplete,onCancel,initialData}){
 const [step,setStep]=useState(0); const [formData,setFormData]=useState(()=>({...INITIAL(activeBatch),...(initialData||{})})); const [errors,setErrors]=useState({});
 useEffect(()=>{const f=e=>{if(e.key==='Escape')onCancel()};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[onCancel]);
 const update=(field,value)=>{setFormData(prev=>{const next={...prev,[field]:value};if(field==='national_id'&&String(value).replace(/\D/g,'').length===14){const p=parseEgyptianNationalId(String(value));if(p?.isValid){next.birth_date=p.birthDate;if(!next.address)next.address='محافظة '+p.governorate}}if(field==='name'&&!prev.father_name){const parts=value.trim().split(/\s+/);if(parts.length>=2)next.father_name=parts.slice(1).join(' ')}return next});setErrors(p=>({...p,[field]:null}))};
 const validate=()=>{const n={};if(step===0){if(!formData.name.trim())n.name='الاسم الرباعي مطلوب';if(String(formData.national_id).replace(/\D/g,'').length!==14)n.national_id='يجب إدخال 14 رقمًا';if(!formData.address.trim())n.address='عنوان السكن مطلوب'}if(step===2&&!formData.father_name.trim())n.father_name='اسم الوالد مطلوب';setErrors(n);return !Object.keys(n).length};
 const next=()=>{if(!validate())return;step<STEPS.length-1?setStep(s=>s+1):onComplete(formData)}; const prev=()=>step===0?onCancel():setStep(s=>s-1); const current=STEPS[step]; const fields=useMemo(()=>current.fields,[current]); const progress=Math.round((step+1)/STEPS.length*100);
 const render=(field)=>{if(OPTIONS[field])return <ChoiceField label={LABELS[field]} value={formData[field]} options={OPTIONS[field]} onChange={v=>update(field,v)}/>;const multi=TEXTAREA.includes(field);const Icon=field==='national_id'||field==='police_number'?CreditCard:field==='address'?MapPin:field.includes('job')||field==='current_job'?Briefcase:null;return <div><label className="block text-xs font-bold text-slate-300 mb-2">{LABELS[field]}</label><div className="relative">{multi?<textarea rows={4} value={formData[field]||''} onChange={e=>update(field,e.target.value)} className="w-full bg-[var(--ui-bg)] border border-[var(--ui-border)] px-4 py-3 text-sm text-white resize-y focus:border-[var(--ui-focus)]"/>:<input type={field==='birth_date'?'date':'text'} inputMode={field==='national_id'?'numeric':undefined} maxLength={field==='national_id'?14:undefined} value={formData[field]||''} onChange={e=>update(field,e.target.value)} className={`w-full bg-[var(--ui-bg)] border px-4 py-3 text-sm text-white ${errors[field]?'border-red-500':'border-[var(--ui-border)]'} focus:border-[var(--ui-focus)]`} placeholder={field==='name'?'الاسم كما هو مدون بالبطاقة':field==='national_id'?'14 رقمًا':''}/>} {Icon&&<span className="absolute left-3 top-3.5 text-slate-600 pointer-events-none"><Icon className="w-4 h-4"/></span>}</div>{errors[field]&&<div className="text-[10px] text-red-300 mt-1">{errors[field]}</div>}</div>};
 return <div className="min-h-screen bg-[var(--ui-bg)] text-white"><header className="no-print bg-[var(--ui-layer-01)] border-b border-[var(--ui-border)] sticky top-0 z-20"><div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-4"><div className="flex items-center justify-between gap-4"><div><div className="text-[10px] font-bold tracking-widest text-[var(--amn-gold-50)]" dir="ltr">AMN-EYE / REGISTRATION</div><h1 className="text-lg font-black mt-1">تسجيل مجند جديد</h1><p className="text-[11px] text-[var(--ui-text-secondary)] mt-1">{activeBatch?.name||'الدفعة النشطة'}</p></div><button onClick={onCancel} className="flex items-center gap-2 px-3 py-2 border border-[var(--ui-border)] text-xs text-slate-400 hover:text-red-300"><X className="w-4 h-4"/> إلغاء</button></div><div className="mt-5 grid grid-cols-3 gap-2">{STEPS.map((item,i)=>{const Icon=item.icon,active=i===step,done=i<step;return <button type="button" key={item.id} onClick={()=>i<=step&&setStep(i)} className={`text-right flex items-center gap-3 px-3 py-3 border transition-colors ${active?'border-[#4c6fff] bg-[#172f7a]/35':done?'border-green-700/50 bg-green-500/5':'border-[var(--ui-border)] opacity-60'}`}><span className={`w-7 h-7 flex items-center justify-center border ${done?'border-green-600 text-green-300':active?'border-[#4c6fff] text-[#9eb4ff]':'border-slate-600 text-slate-500'}`}>{done?<Check className="w-4 h-4"/>:<Icon className="w-4 h-4"/>}</span><span className="hidden sm:block"><span className="block text-[10px] text-slate-500">المرحلة {i+1}</span><span className="text-xs font-bold">{item.label}</span></span></button>})}</div><div className="mt-3 h-1 bg-[var(--ui-bg)]"><div className="h-full bg-[var(--amn-blue-60)] transition-all" style={{width:progress+'%'}}/></div></div></header>
 <main className="max-w-[1400px] mx-auto px-4 sm:px-6 py-8 pb-28"><div className="flex items-start gap-4 mb-7"><div className="w-11 h-11 shrink-0 border border-[#4c6fff] bg-[#172f7a]/30 flex items-center justify-center">{React.createElement(current.icon,{className:'w-5 h-5 text-[#9eb4ff]'})}</div><div><div className="text-xs text-[var(--amn-gold-50)] font-bold">المرحلة {step+1} من {STEPS.length}</div><h2 className="text-2xl font-black mt-1">{current.label}</h2><p className="text-sm text-[var(--ui-text-secondary)] mt-2">{step===0?'التحقق من هوية المجند وبياناته الشخصية الأساسية.':step===1?'البيانات المهنية والملاحظات والتصنيف التشغيلي.':'بيانات الأسرة والملاحظات الأمنية والاجتماعية.'}</p></div></div><section className="amn-card p-4 sm:p-6"><div className={`grid gap-6 ${step===0?'md:grid-cols-2 xl:grid-cols-3':'md:grid-cols-2'}`}>{fields.map(f=><div key={f} className={TEXTAREA.includes(f)||f==='address'?'md:col-span-2':''}>{render(f)}</div>)}</div></section><section className="mt-5 border border-[var(--ui-border)] bg-black/10 p-4 flex gap-3 text-xs text-[var(--ui-text-secondary)]">{step===0?<><Calendar className="w-4 h-4 text-[var(--amn-gold-50)] shrink-0"/><span>عند إدخال رقم قومي صحيح يتم استخراج تاريخ الميلاد والمحافظة تلقائيًا.</span></>:step===1?<><ShieldAlert className="w-4 h-4 text-[var(--amn-gold-50)] shrink-0"/><span>الملاحظات يجب أن تكون موضوعية ودقيقة وتعكس الفحص الفعلي.</span></>:<><Users className="w-4 h-4 text-[var(--amn-gold-50)] shrink-0"/><span>راجع البيانات العائلية قبل الانتقال إلى مرحلة التوثيق المرئي.</span></>}</section></main>
 <footer className="no-print fixed bottom-0 inset-x-0 bg-[var(--ui-layer-01)] border-t border-[var(--ui-border)] z-30"><div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-3 flex items-center justify-between"><button onClick={prev} className="flex items-center gap-2 px-4 py-2.5 border border-[var(--ui-border)] text-xs font-bold text-slate-300 hover:bg-white/5"><ArrowRight className="w-4 h-4"/> {step===0?'إلغاء والعودة':'السابق'}</button><div className="text-[11px] text-slate-500 hidden sm:block">المرحلة {step+1} / {STEPS.length}</div><button onClick={next} className="amn-button-primary flex items-center gap-2 px-5 py-2.5 text-xs font-black">{step===STEPS.length-1?<><Camera className="w-4 h-4"/> الانتقال للتوثيق المرئي</>:<><span>التالي</span><ArrowLeft className="w-4 h-4"/></>}</button></div></footer></div>
}