import React,{useState,useRef,useEffect}from'react';
import{Camera,Video,Check,RotateCcw,Square,CircleDot,Upload,ArrowLeft,ArrowRight,ShieldCheck,AlertTriangle,Loader2,Mic,Info}from'lucide-react';

export default function MediaCapture({formData,onSaveSuccess,onBack,onCancel}){
 const[stage,setStage]=useState('photo'),[photo,setPhoto]=useState(null),[videoBlob,setVideoBlob]=useState(null),[videoUrl,setVideoUrl]=useState(null),[recording,setRecording]=useState(false),[countdown,setCountdown]=useState(30),[cameraError,setCameraError]=useState(null),[saveError,setSaveError]=useState(null),[isSaving,setIsSaving]=useState(false);
 const videoRef=useRef(null),streamRef=useRef(null),recorderRef=useRef(null),chunksRef=useRef([]),timerRef=useRef(null);
 const stopStream=()=>streamRef.current?.getTracks().forEach(t=>t.stop());
 const startCamera=async()=>{setCameraError(null);try{stopStream();const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:true});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream}catch(e){console.error(e);setCameraError('تعذر الوصول إلى الكاميرا أو الميكروفون. يمكنك إعادة المحاولة أو رفع الملفات يدويًا.')}};
 useEffect(()=>{startCamera();return()=>{stopStream();if(timerRef.current)clearInterval(timerRef.current);if(videoUrl)URL.revokeObjectURL(videoUrl)}},[]);
 useEffect(()=>{if(videoRef.current&&streamRef.current&&!photo&&stage==='photo')videoRef.current.srcObject=streamRef.current;if(videoRef.current&&streamRef.current&&!videoUrl&&stage==='video')videoRef.current.srcObject=streamRef.current},[stage,photo,videoUrl]);
 const capturePhoto=()=>{const v=videoRef.current;if(!v||!v.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d');x.translate(c.width,0);x.scale(-1,1);x.drawImage(v,0,0,c.width,c.height);setPhoto(c.toDataURL('image/jpeg',.92))};
 const startRecording=()=>{if(!streamRef.current)return;chunksRef.current=[];let type='video/webm;codecs=vp8,opus';if(!MediaRecorder.isTypeSupported(type))type='video/webm';try{const r=new MediaRecorder(streamRef.current,{mimeType:type});recorderRef.current=r;r.ondataavailable=e=>e.data?.size&&chunksRef.current.push(e.data);r.onstop=()=>{const b=new Blob(chunksRef.current,{type:'video/webm'});setVideoBlob(b);setVideoUrl(URL.createObjectURL(b));setRecording(false)};r.start(500);setRecording(true);setCountdown(30);let sec=30;timerRef.current=setInterval(()=>{sec--;setCountdown(sec);if(sec<=0){clearInterval(timerRef.current);stopRecording()}},1000)}catch(e){setSaveError('تعذر بدء التسجيل: '+e.message)}};
 const stopRecording=()=>{if(timerRef.current)clearInterval(timerRef.current);if(recorderRef.current?.state==='recording')recorderRef.current.stop();setRecording(false)};
 const retakeVideo=()=>{if(videoUrl)URL.revokeObjectURL(videoUrl);setVideoBlob(null);setVideoUrl(null);setCountdown(30)};
 const save=async()=>{setIsSaving(true);setSaveError(null);try{const fd=new FormData();Object.entries(formData).forEach(([k,v])=>fd.append(k,v??''));if(photo){const b=await(await fetch(photo)).blob();fd.append('photo',b,`photo_${formData.national_id||Date.now()}.jpg`)}if(videoBlob)fd.append('video',videoBlob,`video_${formData.national_id||Date.now()}.webm`);const res=await fetch('/api/recruits',{method:'POST',body:fd});if(!res.ok){let d={};try{d=await res.json()}catch{}throw new Error(d.error||'فشل حفظ الملف')}const saved=await res.json();stopStream();onSaveSuccess(saved)}catch(e){console.error(e);setSaveError('خطأ أثناء الحفظ: '+e.message);setIsSaving(false)}};
 const photoUpload=e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setPhoto(r.result);r.readAsDataURL(f)}};
 const videoUpload=e=>{const f=e.target.files?.[0];if(f){setVideoBlob(f);setVideoUrl(URL.createObjectURL(f))}};
 const stageIndex=stage==='photo'?0:stage==='video'?1:2;
 const Stage=({i,icon:Icon,label})=><div className={`flex items-center gap-3 px-3 py-3 border ${i===stageIndex?'border-[#4c6fff] bg-[#172f7a]/30':i<stageIndex?'border-green-700/60 bg-green-500/5':'border-[var(--ui-border)] opacity-60'}`}><span className={`w-7 h-7 flex items-center justify-center border ${i<stageIndex?'text-green-300 border-green-700':i===stageIndex?'text-[#9eb4ff] border-[#4c6fff]':'text-slate-500 border-slate-600'}`}>{i<stageIndex?<Check className="w-4 h-4"/>:<Icon className="w-4 h-4"/>}</span><span className="hidden sm:block"><span className="block text-[10px] text-slate-500">المرحلة {i+1}</span><span className="text-xs font-bold">{label}</span></span></div>;
 return <div className="fixed inset-0 z-50 bg-[var(--ui-bg)] text-white overflow-y-auto"><header className="sticky top-0 z-30 bg-[var(--ui-layer-01)] border-b border-[var(--ui-border)]"><div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-4"><div className="flex justify-between items-start gap-4"><div><div className="text-[10px] font-bold tracking-widest text-[var(--amn-gold-50)]" dir="ltr">AMN-EYE / VISUAL DOCUMENTATION</div><h1 className="text-lg font-black mt-1">التوثيق المرئي للمجند</h1><p className="text-xs text-[var(--ui-text-secondary)] mt-1">{formData.name} <span className="mx-2 text-slate-600">•</span> {formData.national_id}</p></div><button onClick={onCancel} className="px-3 py-2 border border-[var(--ui-border)] text-xs text-slate-400 hover:text-red-300">إلغاء</button></div><div className="grid grid-cols-3 gap-2 mt-5"><Stage i={0} icon={Camera} label="الصورة الشخصية"/><Stage i={1} icon={Video} label="التوثيق بالفيديو"/><Stage i={2} icon={ShieldCheck} label="المراجعة والحفظ"/></div><div className="h-1 bg-[var(--ui-bg)] mt-3"><div className="h-full bg-[var(--amn-blue-60)] transition-all" style={{width:`${(stageIndex+1)/3*100}%`}}/></div></div></header>
 <main className="max-w-[1400px] mx-auto px-4 sm:px-6 py-7 pb-28">
 {cameraError&&<div className="mb-5 border border-yellow-700/50 bg-yellow-500/5 p-4 flex flex-col sm:flex-row gap-3 justify-between text-xs text-yellow-200"><div className="flex gap-3"><AlertTriangle className="w-5 h-5 shrink-0"/><span>{cameraError}</span></div><button onClick={startCamera} className="border border-yellow-700/60 px-3 py-2 font-bold">إعادة المحاولة</button></div>}
 {saveError&&<div className="mb-5 border border-red-700/60 bg-red-500/5 p-4 flex gap-3 text-xs text-red-200"><AlertTriangle className="w-5 h-5 shrink-0"/><span>{saveError}</span></div>}
 {stage==='photo'&&<section className="grid xl:grid-cols-[1fr_320px] gap-5"><div className="amn-card overflow-hidden"><div className="p-4 border-b border-[var(--ui-border)] flex justify-between"><div><div className="text-[10px] text-[var(--amn-gold-50)] font-bold">المرحلة 01</div><h2 className="font-black mt-1">الصورة الشخصية</h2></div><span className={`text-[10px] px-2 py-1 h-fit border ${photo?'border-green-700 text-green-300':'border-[#3e5fbd] text-[#9eb4ff]'}`}>{photo?'تم الالتقاط':'بانتظار الالتقاط'}</span></div><div className="p-4"><div className="relative w-full aspect-video bg-black border border-[var(--ui-border)] overflow-hidden">{!photo?<><video ref={videoRef} autoPlay playsInline muted className="w-full h-full object-cover scale-x-[-1]"/><div className="absolute inset-0 flex items-center justify-center pointer-events-none"><div className="w-40 h-56 sm:w-48 sm:h-64 border-2 border-dashed border-[#9eb4ff]/70 rounded-[50%]"/></div><div className="absolute top-3 right-3 flex items-center gap-2 bg-black/70 px-3 py-1 text-[10px]"><span className="w-2 h-2 bg-green-400 animate-pulse"/>{cameraError?'الكاميرا غير متاحة':'بث مباشر'}</div></>:<img src={photo} alt="صورة المجند" className="w-full h-full object-cover"/>}</div><div className="mt-4 flex flex-wrap gap-2">{!photo?<><button onClick={capturePhoto} disabled={!!cameraError} className="amn-button-primary flex items-center gap-2 px-5 py-3 text-xs font-black disabled:opacity-40"><Camera className="w-4 h-4"/>التقاط الصورة</button><label className="flex items-center gap-2 px-4 py-3 border border-[var(--ui-border)] text-xs font-bold cursor-pointer"><Upload className="w-4 h-4"/>رفع صورة<input className="hidden" type="file" accept="image/*" onChange={photoUpload}/></label></>:<><button onClick={()=>setPhoto(null)} className="flex items-center gap-2 px-4 py-3 border border-[var(--ui-border)] text-xs"><RotateCcw className="w-4 h-4"/>إعادة الالتقاط</button><button onClick={()=>setStage('video')} className="amn-button-primary flex items-center gap-2 px-5 py-3 text-xs font-black">اعتماد الصورة<ArrowLeft className="w-4 h-4"/></button></>}</div></div></div><aside className="amn-card p-5 h-fit"><Info className="w-5 h-5 text-[var(--amn-gold-50)]"/><h3 className="font-black mt-3">إرشادات الصورة</h3><ul className="mt-3 space-y-3 text-xs text-[var(--ui-text-secondary)]"><li>• وجه المجند داخل الإطار الإرشادي.</li><li>• تأكد من وضوح الوجه والإضاءة.</li><li>• تجنب الخلفية المزدحمة.</li><li>• راجع الصورة قبل الاعتماد.</li></ul></aside></section>}
 {stage==='video'&&<section className="grid xl:grid-cols-[1fr_320px] gap-5"><div className="amn-card overflow-hidden"><div className="p-4 border-b border-[var(--ui-border)] flex justify-between"><div><div className="text-[10px] text-[var(--amn-gold-50)] font-bold">المرحلة 02</div><h2 className="font-black mt-1">التوثيق بالفيديو</h2></div>{recording&&<div className="flex items-center gap-2 text-red-300 text-xs font-bold"><CircleDot className="w-4 h-4 animate-pulse"/>REC {countdown}s</div>}</div><div className="p-4"><div className="relative w-full aspect-video bg-black border border-[var(--ui-border)]">{!videoUrl?<video ref={videoRef} autoPlay playsInline muted className="w-full h-full object-cover scale-x-[-1]"/>:<video src={videoUrl} controls className="w-full h-full object-contain"/>}{!videoUrl&&!recording&&<div className="absolute inset-0 bg-black/55 flex items-center justify-center p-6 text-center"><div><Mic className="w-7 h-7 mx-auto text-[var(--amn-gold-50)] mb-3"/><h3 className="font-bold">مقطع توثيقي لمدة تصل إلى 30 ثانية</h3><p className="text-xs text-slate-400 mt-2">يذكر المجند اسمه الرباعي ومؤهله ومحل إقامته بصوت واضح.</p></div></div>}</div><div className="mt-4 flex flex-wrap gap-2">{!videoUrl?recording?<button onClick={stopRecording} className="flex items-center gap-2 px-5 py-3 border border-red-600 text-red-200 text-xs font-black"><Square className="w-4 h-4 fill-red-400"/>إنهاء التسجيل ({countdown} ث)</button>:<><button onClick={startRecording} disabled={!!cameraError} className="flex items-center gap-2 px-5 py-3 bg-red-700 hover:bg-red-600 text-xs font-black disabled:opacity-40"><CircleDot className="w-4 h-4"/>بدء التسجيل</button><label className="flex items-center gap-2 px-4 py-3 border border-[var(--ui-border)] text-xs cursor-pointer"><Upload className="w-4 h-4"/>رفع فيديو<input className="hidden" type="file" accept="video/*" onChange={videoUpload}/></label></>:<><button onClick={retakeVideo} className="flex items-center gap-2 px-4 py-3 border border-[var(--ui-border)] text-xs"><RotateCcw className="w-4 h-4"/>إعادة التسجيل</button><button onClick={()=>setStage('review')} className="amn-button-primary flex items-center gap-2 px-5 py-3 text-xs font-black">اعتماد الفيديو<ArrowLeft className="w-4 h-4"/></button></>}</div></div></div><aside className="amn-card p-5 h-fit"><Video className="w-5 h-5 text-[var(--amn-gold-50)]"/><h3 className="font-black mt-3">تعليمات التسجيل</h3><p className="mt-3 text-xs leading-6 text-[var(--ui-text-secondary)]">التسجيل التلقائي يتوقف بعد 30 ثانية، ويمكن إنهاؤه يدويًا. راجع الصوت والصورة قبل الاعتماد.</p></aside></section>}
 {stage==='review'&&<section className="grid xl:grid-cols-[1fr_320px] gap-5"><div className="amn-card p-5"><div className="text-[10px] text-[var(--amn-gold-50)] font-bold">المرحلة 03</div><h2 className="text-xl font-black mt-1">مراجعة واعتماد الملف</h2><p className="text-sm text-[var(--ui-text-secondary)] mt-2">تأكد من اكتمال البيانات والتوثيق المرئي قبل الحفظ النهائي.</p><div className="mt-6 grid md:grid-cols-2 gap-4"><div className="border border-[var(--ui-border)] p-3"><div className="text-xs font-bold mb-3 flex justify-between">الصورة الشخصية <Check className="w-4 h-4 text-green-300"/></div><img src={photo} alt="" className="w-full aspect-video object-cover bg-black"/></div><div className="border border-[var(--ui-border)] p-3"><div className="text-xs font-bold mb-3 flex justify-between">الفيديو <Check className="w-4 h-4 text-green-300"/></div><video src={videoUrl} controls className="w-full aspect-video object-contain bg-black"/></div></div></div><aside className="amn-card p-5 h-fit"><ShieldCheck className="w-6 h-6 text-[var(--amn-gold-50)]"/><h3 className="font-black mt-3">جاهز للحفظ</h3><p className="mt-2 text-xs text-[var(--ui-text-secondary)]">سيتم إنشاء سجل المجند وحفظ الوسائط المرتبطة به.</p><button onClick={save} disabled={isSaving} className="mt-5 w-full amn-button-primary flex items-center justify-center gap-2 px-4 py-3 text-xs font-black disabled:opacity-50">{isSaving?<><Loader2 className="w-4 h-4 animate-spin"/>جاري الحفظ...</>:<><ShieldCheck className="w-4 h-4"/>حفظ واعتماد الملف</>}</button></aside></section>}
 </main><footer className="fixed bottom-0 inset-x-0 bg-[var(--ui-layer-01)] border-t border-[var(--ui-border)] z-30"><div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-3 flex justify-between"><button onClick={()=>stage==='photo'?onBack():setStage(stage==='review'?'video':'photo')} className="flex gap-2 items-center px-4 py-2 border border-[var(--ui-border)] text-xs"><ArrowRight className="w-4 h-4"/>السابق</button>{stage!=='review'&&<button onClick={save} disabled={isSaving} className="text-xs text-slate-500 hover:text-slate-300">حفظ بدون فيديو</button>}</div></footer></div>
}