import React,{useEffect,useState,useRef}from'react';
import{X,Printer,Trash2,Video,Camera,User,Home,Briefcase,ShieldAlert,Activity,Users,IdCard,Download,FileText,ChevronLeft,CheckCircle2,Calendar}from'lucide-react';
import LockerCard from './LockerCard';import html2canvas from 'html2canvas';

const TABS=[['overview','نظرة عامة',User],['personal','البيانات الأساسية',FileText],['family','الأسرة والتحريات',Users],['media','الوسائط',Camera]];
const Field=({label,value,mono=false})=><div className="border border-[var(--ui-border)] bg-[var(--ui-bg)] p-3 min-h-[72px]"><div className="text-[10px] text-[var(--ui-text-secondary)] mb-1">{label}</div><div className={`text-sm font-bold text-white break-words ${mono?'font-mono':''}`}>{value||'غير مدون'}</div></div>;
const EmptyMedia=({icon:Icon,text})=><div className="w-full h-full flex flex-col items-center justify-center text-slate-500 text-xs"><Icon className="w-10 h-10 mb-2 stroke-1"/>{text}</div>;

export default function RecruitModal({recruit,onClose,onPrint,onDelete}){
 const[tab,setTab]=useState('overview'),[showCard,setShowCard]=useState(false);const cardRef=useRef(null);
 useEffect(()=>{const f=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[onClose]);
 if(!recruit)return null;
 const downloadCard=async()=>{if(!cardRef.current)return;try{const c=await html2canvas(cardRef.current,{scale:2.5,useCORS:true,allowTaint:true,backgroundColor:'#fff'});const a=document.createElement('a');a.download=`كارت_دولاب_${recruit.name.replace(/\s+/g,'_')}.png`;a.href=c.toDataURL('image/png');a.click()}catch(e){console.error(e)}};
 const personal=<div className="space-y-5"><Section title="البيانات الأساسية" icon={User}><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Field label="رقم الشرطة" value={recruit.police_number} mono/><Field label="السرية / الكتيبة" value={recruit.company}/><Field label="الرقم القومي" value={recruit.national_id} mono/><Field label="تاريخ الميلاد" value={recruit.birth_date} mono/><Field label="الديانة" value={recruit.religion}/><Field label="المؤهل الدراسي" value={recruit.qualification}/><Field label="الحالة الاجتماعية" value={recruit.wife}/><Field label="إجادة القراءة والكتابة" value={recruit.literacy}/></div></Section><Section title="السكن والعمل" icon={Briefcase}><div className="grid sm:grid-cols-2 gap-3"><div className="sm:col-span-2"><Field label="عنوان السكن" value={recruit.address}/></div><Field label="المهنة الحالية" value={recruit.current_job}/><Field label="مهن وحرف أخرى" value={recruit.other_jobs}/><div className="sm:col-span-2"><Field label="السفر خارج البلاد" value={recruit.travel_abroad}/></div></div></Section></div>;
 const family=<div className="space-y-5"><Section title="بيانات الأسرة" icon={Users}><div className="grid sm:grid-cols-2 gap-3"><Field label="اسم الوالد" value={recruit.father_name}/><Field label="مهنة الوالد" value={recruit.father_job}/><Field label="اسم الأم" value={recruit.mother_name}/><Field label="مهنة الأم" value={recruit.mother_job}/><div className="sm:col-span-2"><Field label="الحالة الاجتماعية للعائلة" value={recruit.family_social_status}/></div></div></Section><Section title="الفحص الأمني والتحريات" icon={ShieldAlert}><div className="space-y-3"><Field label="فحص الإخوة والأخوات" value={recruit.siblings_check}/><Field label="الحالة السياسية والجنائية للعائلة" value={recruit.family_security_status}/></div></Section></div>;
 const media=<div className="grid lg:grid-cols-2 gap-5"><MediaCard title="الصورة الشخصية" icon={Camera}>{recruit.photo_path?<img src={recruit.photo_path} alt={recruit.name} className="w-full aspect-[4/3] object-cover bg-black"/>:<EmptyMedia icon={User} text="لا توجد صورة مسجلة"/>}</MediaCard><MediaCard title="الفيديو التوثيقي" icon={Video}>{recruit.video_path?<video src={recruit.video_path} controls className="w-full aspect-video object-contain bg-black"/>:<EmptyMedia icon={Video} text="لا يوجد مقطع فيديو مسجل"/>}</MediaCard></div>;
 const overview=<div className="grid xl:grid-cols-[1.4fr_1fr] gap-5"><div className="space-y-5"><Section title="ملخص الملف" icon={CheckCircle2}><div className="grid sm:grid-cols-2 gap-3"><Field label="الدفعة" value={recruit.batch_name}/><Field label="تاريخ الحضور" value={recruit.attendance_date}/><Field label="رقم الشرطة" value={recruit.police_number}/><Field label="السرية" value={recruit.company}/></div></Section><Section title="المناظرة والفحص الطبي" icon={Activity}><div className="space-y-3"><Field label="مناظرة المجند" value={recruit.inspection}/><Field label="الحالة المرضية" value={recruit.medical_status}/></div></Section></div><div className="space-y-5"><MediaCard title="الصورة الشخصية" icon={Camera} compact>{recruit.photo_path?<img src={recruit.photo_path} alt={recruit.name} className="w-full aspect-[4/3] object-cover bg-black"/>:<EmptyMedia icon={User} text="لا توجد صورة"/>}</MediaCard><div className="border border-[var(--ui-border)] p-4"><div className="text-xs font-bold mb-3">حالة اكتمال الملف</div><div className="space-y-2 text-xs">{[['البيانات الأساسية',true],['الصورة الشخصية',!!recruit.photo_path],['الفيديو التوثيقي',!!recruit.video_path]].map(([l,ok])=><div key={l} className="flex justify-between border-b border-[var(--ui-border)] pb-2"><span>{l}</span><span className={ok?'text-green-300':'text-yellow-300'}>{ok?'مكتمل':'غير متوفر'}</span></div>)}</div></div></div></div>;
 const content=tab==='overview'?overview:tab==='personal'?personal:tab==='family'?family:media;
 return <div className="fixed inset-0 z-50 bg-black/75 flex justify-end" dir="rtl"><div className="w-full max-w-[1180px] h-full bg-[var(--ui-layer-01)] border-r border-[var(--ui-border)] flex flex-col shadow-2xl animate-in slide-in-from-right duration-200"><header className="shrink-0 border-b border-[var(--ui-border)]"><div className="px-4 sm:px-6 py-4 flex items-start justify-between gap-4"><div className="flex gap-4 min-w-0"><div className="w-14 h-14 shrink-0 border border-[#4c6fff] bg-[#172f7a]/30 overflow-hidden flex items-center justify-center">{recruit.photo_path?<img src={recruit.photo_path} alt="" className="w-full h-full object-cover"/>:<User className="w-6 h-6 text-[#9eb4ff]"/>}</div><div className="min-w-0"><div className="text-[10px] tracking-widest font-bold text-[var(--amn-gold-50)]" dir="ltr">AMN-EYE / RECRUIT DOSSIER</div><h2 className="text-xl sm:text-2xl font-black mt-1 truncate">{recruit.name}</h2><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-[var(--ui-text-secondary)]"><span>رقم الشرطة: <b className="text-slate-200">{recruit.police_number||'—'}</b></span><span>الدفعة: <b className="text-slate-200">{recruit.batch_name||'—'}</b></span><span>{recruit.company||'—'}</span></div></div></div><div className="flex gap-2 shrink-0"><button onClick={()=>setShowCard(!showCard)} className="hidden sm:flex items-center gap-2 px-3 py-2 border border-[var(--ui-border)] text-xs hover:bg-white/5"><IdCard className="w-4 h-4"/>كارت الدولاب</button><button onClick={()=>onPrint(recruit)} className="hidden sm:flex items-center gap-2 px-3 py-2 amn-button-primary text-xs"><Printer className="w-4 h-4"/>طباعة</button><button onClick={onClose} className="p-2 border border-[var(--ui-border)] hover:bg-white/5"><X className="w-5 h-5"/></button></div></div><nav className="px-4 sm:px-6 flex overflow-x-auto border-t border-[var(--ui-border)]">{TABS.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 flex items-center gap-2 px-4 py-3 text-xs font-bold border-b-2 ${tab===id?'border-[#4c6fff] text-white bg-[#172f7a]/15':'border-transparent text-slate-500 hover:text-slate-300'}`}><Icon className="w-4 h-4"/>{label}</button>)}</nav></header>
 {showCard&&<div className="shrink-0 border-b border-[var(--ui-border)] p-4 bg-black/15"><div className="flex items-center justify-between mb-3"><div className="text-xs font-bold flex items-center gap-2"><IdCard className="w-4 h-4 text-[var(--amn-gold-50)]"/>معاينة كارت الدولاب</div><button onClick={downloadCard} className="flex gap-2 items-center text-xs px-3 py-2 border border-[var(--ui-border)] hover:bg-white/5"><Download className="w-4 h-4"/>تحميل PNG</button></div><div className="flex justify-center"><div className="shadow-xl overflow-hidden"><LockerCard ref={cardRef} recruit={recruit} scale={0.72}/></div></div></div>}
 <main className="flex-1 overflow-y-auto p-4 sm:p-6 bg-[var(--ui-bg)]">{content}</main><footer className="shrink-0 border-t border-[var(--ui-border)] px-4 sm:px-6 py-3 flex justify-between items-center bg-[var(--ui-layer-01)]"><button onClick={onClose} className="flex items-center gap-2 text-xs text-slate-400 hover:text-white"><ChevronLeft className="w-4 h-4"/>إغلاق الملف</button><div className="flex gap-2"><button onClick={()=>onPrint(recruit)} className="sm:hidden flex items-center gap-2 px-3 py-2 amn-button-primary text-xs"><Printer className="w-4 h-4"/>طباعة</button><button onClick={()=>{if(confirm(`هل أنت متأكد من حذف ملف المجند "${recruit.name}"؟`))onDelete(recruit.id)}} className="flex items-center gap-2 px-3 py-2 border border-red-900/60 text-red-300 hover:bg-red-500/10 text-xs"><Trash2 className="w-4 h-4"/>حذف الملف</button></div></footer></div></div>
}
function Section({title,icon:Icon,children}){return <section className="border border-[var(--ui-border)] bg-[var(--ui-layer-01)]"><div className="px-4 py-3 border-b border-[var(--ui-border)] flex gap-2 items-center"><Icon className="w-4 h-4 text-[var(--amn-gold-50)]"/><h3 className="text-xs font-black">{title}</h3></div><div className="p-4">{children}</div></section>}
function MediaCard({title,icon:Icon,children}){return <section className="border border-[var(--ui-border)] bg-[var(--ui-layer-01)]"><div className="px-4 py-3 border-b border-[var(--ui-border)] flex gap-2 items-center"><Icon className="w-4 h-4 text-[var(--amn-gold-50)]"/><h3 className="text-xs font-black">{title}</h3></div><div className="p-3 min-h-[230px]">{children}</div></section>}